build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "10"

configuration: Release
platform:
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - SET PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - git submodule update --init --recursive
  - npm i

test_script:
  - node --version
  - npm --version

before_deploy:
  - SET ARCHIVE_NAME=%APPVEYOR_REPO_TAG_NAME%-win32-%PLATFORM%.tar.gz
  - npm run prebuild
  - tar -zcvf "%ARCHIVE_NAME%" -C prebuilds .
  - appveyor PushArtifact %ARCHIVE_NAME%

deploy:
  - provider: GitHub
    artifact: $(ARCHIVE_NAME)
    draft: false
    prerelease: true
    auth_token:
      secure: cenas-appveyor
    on:
      appveyor_repo_tag: true
      nodejs_version: "10"
