build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "10"

configuration: Release
platform:
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - SET PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - git submodule update --init --recursive
  - npm i

test_script:
  - node --version
  - npm --version

artifacts:
  - path: win32-x64
    name: node.abi64.node

before_deploy:
    - cp build\release\node-lmdb.node win32-x64\node.abi64.node

deploy:
  - provider: GitHub
    artifact: node.abi64.node
    draft: false
    prerelease: true
    auth_token:
      secure: HzdCSCozmgsygSGH7gTddZR3htpkU3W5EhkFzAuYVRJmWPAbCn6bulck6aFwHBeR
    on:
      appveyor_repo_tag: true
      nodejs_version: "10"
